import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import User from '@/components/User';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${inter.className} game-body`}>
        
        <User/>
        {children}  
      </body>
    </html>
      
  );
}
