import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${inter.className} game-body`}>
        <nav className="game-nav">
            <div className="user-nav-details-container">
                <Image className="user-img" src="/icons/userIcon.png" alt="User placeholder" width={100} height={30}></Image>
                <div className="level-bar-container">
                    <div className="level-bar"></div>
                </div>
                <p className="user-level">Nv.<span>##</span></p>
            </div>

            <button className="almanac-btn"> Almanaque </button>

            <div className="wish-nav-detail-container">
                <Image className="wish-img" src="/icons/star.png" alt="Game wish image" width={100} height={30}></Image>
                <div className="wish-amount">##</div>
                <button className="more-wishes-btn"> + </button>
            </div>

        </nav>
        {children}

        
      </body>
    </html>
      
  );
}
